version: '3.7'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

  porter:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379
      - INPUT_FILE=./imports/ports.json
      - IGNORE_ERRORS=true
    volumes:
      - ./testdata:/imports